### ISSUE TITLE
require_tree argument must be a directory

### ISSUE THREAD

**Issue by kethomassen** [madchatter/mad_chatter#10]
Getting this on Rails 4 using Thin.

> Sprockets::ArgumentError at /
>  require_tree argument must be a directory
>   (in /Users/kristian/.rvm/gems/ruby-2.0.0-p247/bundler/gems/mad_chatter-ee18ab091e83/app/assets/javascripts/mad_chatter/application.js:19)

**Comment by andrewhavens** [comment]
Thanks @kethomassen. I forgot that git does not track empty directories, so it was working for me locally because I manually created the directory. The problem should be fixed now.
